global:
  scrape_interval: 5s

scrape_configs:
  # Scrape Prometheus itself (optional)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Scrape node-exporter untuk CPU, RAM, dll
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
