name: Deploy ke VPS

on:
  push:
    branches: [ "main" ]   # jalankan workflow setiap push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy ke VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}      # IP / domain VPS
          username: ${{ secrets.VPS_USER }}  # user SSH VPS (misal: bnsp19)
          key: ${{ secrets.VPS_KEY }}        # private key SSH
          port: 22
          script:  |
            cd ~/proyek-cloud
            git pull
            docker compose down
            docker compose up -d --build
